In [3]:
# import libraries
import pandas as pd
import geopandas as gpd 
import folium

/home/azash/.local/lib/python3.8/site-packages/geopandas/_compat.py:112: UserWarning: The Shapely GEOS version (3.10.2-CAPI-1.16.0) is incompatible with the GEOS version PyGEOS was compiled with (3.10.3-CAPI-1.16.1). Conversions between both will be slow.
  warnings.warn(

In [4]:
# read in the Australian suburbs shapesfiles 
australia_sf = gpd.read_file("../data/raw/shapefiles/Statistical_area_level2/SA2_2021_AUST_GDA2020.shp")
australia_sf.head(3)

,SA2_CODE21,SA2_NAME21,CHG_FLAG21,CHG_LBL21,SA3_CODE21,SA3_NAME21,SA4_CODE21,SA4_NAME21,GCC_CODE21,GCC_NAME21,STE_CODE21,STE_NAME21,AUS_CODE21,AUS_NAME21,AREASQKM21,LOCI_URI21,geometry
0,101021007,Braidwood,0,No change,10102,Queanbeyan,101,Capital Region,1RNSW,Rest of NSW,1,New South Wales,AUS,Australia,3418.3525,http://linked.data.gov.au/dataset/asgsed3/SA2/...,"POLYGON ((149.58424 -35.44426, 149.58444 -35.4..."
1,101021008,Karabar,0,No change,10102,Queanbeyan,101,Capital Region,1RNSW,Rest of NSW,1,New South Wales,AUS,Australia,6.9825,http://linked.data.gov.au/dataset/asgsed3/SA2/...,"POLYGON ((149.21899 -35.36738, 149.21800 -35.3..."
2,101021009,Queanbeyan,0,No change,10102,Queanbeyan,101,Capital Region,1RNSW,Rest of NSW,1,New South Wales,AUS,Australia,4.7620,http://linked.data.gov.au/dataset/asgsed3/SA2/...,"POLYGON ((149.21326 -35.34325, 149.21619 -35.3..."

In [6]:
# seperate suburbs that are in Victoria
vic_sf = australia_sf[australia_sf['STE_NAME21'] == 'Victoria']

In [6]:
# create a JSON
geoJSON = vic_sf[['SA2_NAME21', 'geometry']].drop_duplicates('SA2_NAME21').to_json()

In [3]:
# read in bus stop location shapesfiles 
bus_sf = gpd.read_file("../data/raw/shapefiles/Bus_stop_location/PTV_bus/PTV_METRO_BUS_STOP.shp")
bus_sf.head()

,STOP_ID,STOP_NAME,LATITUDE,LONGITUDE,TICKETZONE,ROUTEUSSP,geometry
0,10185,Bonnie View Rd/Maroondah Hwy (Croydon North),-37.780920,145.288145,2,670,POINT (145.28815 -37.78091)
1,10186,Primrose Rd/Maroondah Hwy (Croydon North),-37.774626,145.292843,2,670,POINT (145.29285 -37.77461)
2,10187,Exeter Rd/Maroondah Hwy (Croydon North),-37.770446,145.295459,2,670,POINT (145.29546 -37.77043)
3,10188,Maroondah Golf Park/Maroondah Hwy (Chirnside P...,-37.766346,145.301775,2,670,POINT (145.30178 -37.76633)
4,10189,Old Melbourne Rd/Maroondah Hwy (Chirnside Park),-37.765276,145.304410,2,670,POINT (145.30442 -37.76526)

In [7]:
# read in train station location shapesfiles 
train_sf = gpd.read_file("../data/raw/shapefiles/Train_station_location/PTV_train/PTV_METRO_TRAIN_STATION.shp")
train_sf.head()

,STOP_ID,STOP_NAME,LATITUDE,LONGITUDE,TICKETZONE,ROUTEUSSP,geometry
0,19970,Royal Park Railway Station (Parkville),-37.781193,144.952301,1,Upfield,POINT (144.95231 -37.78118)
1,19971,Flemington Bridge Railway Station (North Melbo...,-37.788140,144.939323,1,Upfield,POINT (144.93933 -37.78813)
2,19972,Macaulay Railway Station (North Melbourne),-37.794267,144.936166,1,Upfield,POINT (144.93617 -37.79425)
3,19973,North Melbourne Railway Station (West Melbourne),-37.807419,144.942570,1,"Flemington,Sunbury,Upfield,Werribee,Williamsto...",POINT (144.94258 -37.80741)
4,19974,Clifton Hill Railway Station (Clifton Hill),-37.788657,144.995417,1,"Mernda,Hurstbridge",POINT (144.99542 -37.78864)

In [9]:
# read in tram stop location shapesfiles 
tram_sf = gpd.read_file("../data/raw/shapefiles/Tram_stop_location/PTV_tram/PTV_METRO_TRAM_STOP.shp")
tram_sf.head()

,STOP_ID,STOP_NAME,LATITUDE,LONGITUDE,TICKETZONE,ROUTEUSSP,geometry
0,18730,134-Merribell Ave/Nicholson St (Coburg),-37.744359,144.977728,1,1,POINT (144.97773 -37.74435)
1,18732,44-Deepdene Park/Whitehorse Rd (Balwyn),-37.811375,145.068671,1,109,POINT (145.06868 -37.81136)
2,18733,45-Hardwicke St/Whitehorse Rd (Balwyn),-37.811750,145.071785,1,109,POINT (145.07179 -37.81174)
3,18734,46-Balwyn Cinema/Whitehorse Rd (Balwyn),-37.812242,145.075930,1,109,POINT (145.07594 -37.81223)
4,18735,47-Balwyn Rd/Whitehorse Rd (Balwyn),-37.812919,145.081524,"1,2",109,POINT (145.08153 -37.81291)

In [3]:
# read in regional bus stop location shapesfiles 
busreg_sf = gpd.read_file("../data/raw/shapefiles/Bus_stop_location_reg/PTV_bus_reg/PTV_REGIONAL_BUS_STOP.shp")
busreg_sf.head()

,STOP_ID,STOP_NAME,LATITUDE,LONGITUDE,ROUTEUSSP,geometry
0,23195,Andrew St/Union St (Kilmore),-37.290492,144.952280,None,POINT (144.95229 -37.29048)
1,23197,Wellington Square SC/Queen St (Wallan),-37.412990,144.978019,Wallan 1,POINT (144.97802 -37.41298)
2,23202,Aquamoves/Tom Collins Dr (Shepparton),-36.386027,145.394445,9,POINT (145.39445 -36.38601)
3,23224,West End Caravan Park/Murray Valley Hwy (Yarra...,-36.022176,145.977047,None,POINT (145.97705 -36.02216)
4,23225,Jane Rd/Fiona Dr (Yarrawonga),-36.006707,146.025958,None,POINT (146.02596 -36.00669)

In [10]:
# read in regional train station location shapesfiles 
trainreg_sf = gpd.read_file("../data/raw/shapefiles/Train_station_location_reg/PTV_train_reg/PTV_REGIONAL_TRAIN_STATION.shp")
trainreg_sf.head()

,STOP_ID,STOP_NAME,LATITUDE,LONGITUDE,geometry
0,17204,Wallan Railway Station (Wallan),-37.416861,145.005372,POINT (145.00538 -37.41685)
1,19980,Melton Railway Station (Melton South),-37.703359,144.572216,POINT (144.57222 -37.70335)
2,19981,Rockbank Railway Station (Rockbank),-37.729261,144.650631,POINT (144.65064 -37.72925)
3,19982,Deer Park Railway Station (Deer Park),-37.777764,144.772304,POINT (144.77231 -37.77775)
4,19998,Sunbury Railway Station (Sunbury),-37.579206,144.728165,POINT (144.72817 -37.57919)

In [14]:
# make an empty folium map
_map = folium.Map(location=[-37.78, 145.29], tiles="Stamen Terrain", zoom_start=10, preferCanvas=True)

# overlay of Victoria suburbs
_map.add_child(folium.Choropleth(
    geo_data=geoJSON,
    name='choropleth',
))

# add marker one by one on the map for each
# bus stop locations
for i in range(0, len(bus_sf)):
   folium.Circle(
      location=[bus_sf.iloc[i]['LATITUDE'], bus_sf.iloc[i]['LONGITUDE']],
      popup=bus_sf.iloc[i]['STOP_NAME'],
      radius=10,
      color='crimson',
      fill=True,
      fill_color='crimson'
   ).add_to(_map)

# train station locations
for i in range(0, len(train_sf)):
   folium.Circle(
      location=[train_sf.iloc[i]['LATITUDE'], train_sf.iloc[i]['LONGITUDE']],
      popup=train_sf.iloc[i]['STOP_NAME'],
      radius=100,
      color='yellow',
      fill=True,
      fill_color='yellow'
   ).add_to(_map)

# tram stop locations
for i in range(0, len(tram_sf)):
   folium.Circle(
      location=[tram_sf.iloc[i]['LATITUDE'], tram_sf.iloc[i]['LONGITUDE']],
      popup=tram_sf.iloc[i]['STOP_NAME'],
      radius=20,
      color='green',
      fill=True,
      fill_color='green'
   ).add_to(_map)

# regional bus stop locations
for i in range(0, len(busreg_sf)):
   folium.Circle(
      location=[busreg_sf.iloc[i]['LATITUDE'], busreg_sf.iloc[i]['LONGITUDE']],
      popup=busreg_sf.iloc[i]['STOP_NAME'],
      radius=20,
      color='crimson',
      fill=True,
      fill_color='crimson'
   ).add_to(_map) 

# regional train station locations
for i in range(0, len(trainreg_sf)):
   folium.Circle(
      location=[trainreg_sf.iloc[i]['LATITUDE'], trainreg_sf.iloc[i]['LONGITUDE']],
      popup=trainreg_sf.iloc[i]['STOP_NAME'],
      radius=100,
      color='yellow',
      fill=True,
      fill_color='yellow'
   ).add_to(_map)

# save map
_map.save('../plots/foliumpublictransportmap.html')

In [15]:
# display map
_map